# Generated by Django 5.0 on 2025-12-09 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_school_updated_at_school_website_and_more'),
        ('students', '0004_alter_student_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.academicsession'),
        ),
    ]
