# Generated by Django 5.0 on 2025-12-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='samagra_id',
            field=models.IntegerField(default='120641541', max_length=9),
            preserve_default=False,
        ),
    ]
