# Generated by Django 5.0 on 2025-12-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_samagra_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='samagra_id',
            field=models.CharField(max_length=9),
        ),
    ]
