# Generated by Django 5.0 on 2025-12-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_school_updated_at_school_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='institute_type',
            field=models.CharField(choices=[('school', 'School (Standard)'), ('coaching', 'Coaching Institute'), ('madrasa', 'Madrasa (Islamic)')], default='school', max_length=20),
        ),
    ]
