# Generated by Django 5.0 on 2025-12-09 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_subject'),
        ('core', '0002_remove_school_updated_at_school_website_and_more'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicsession'),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='core.school'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('school', 'class_grade', 'category')},
        ),
    ]
